import SwiftUI

/// Compact narrative panel rendered inside the expanded week card,
/// above the session list. Gives athletes a short "what this week is
/// for" line in coach voice — generated by
/// `WeeklyNarrativeGenerator` — so the plan stops reading as raw
/// session cards and starts reading as a plan.
struct WeeklyNarrativeCard: View {
    let narrative: WeeklyNarrativeGenerator.Narrative
    /// Phase tint used for the leading icon and subtle background so
    /// the card's colour identity matches the week it belongs to.
    let phaseTint: Color

    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 8) {
                Image(systemName: "text.quote")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(phaseTint)
                Text(narrative.title.uppercased())
                    .font(.caption2.weight(.bold))
                    .tracking(0.6)
                    .foregroundStyle(phaseTint)
            }

            Text(narrative.body)
                .font(.subheadline)
                .foregroundStyle(Theme.Colors.label)
                .fixedSize(horizontal: false, vertical: true)
                .lineSpacing(1.5)

            if let goal = narrative.goal {
                HStack(spacing: 6) {
                    Image(systemName: "target")
                        .font(.caption2.weight(.semibold))
                    Text(goal)
                        .font(.caption)
                }
                .foregroundStyle(phaseTint)
                .padding(.horizontal, 10)
                .padding(.vertical, 5)
                .background(
                    Capsule().fill(phaseTint.opacity(colorScheme == .dark ? 0.18 : 0.10))
                )
                .overlay(
                    Capsule().stroke(phaseTint.opacity(0.25), lineWidth: 0.5)
                )
            }
        }
        .padding(Theme.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: Theme.CornerRadius.md)
                .fill(LinearGradient(
                    colors: [
                        phaseTint.opacity(colorScheme == .dark ? 0.14 : 0.06),
                        phaseTint.opacity(colorScheme == .dark ? 0.03 : 0.01)
                    ],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                ))
        )
        .overlay(
            RoundedRectangle(cornerRadius: Theme.CornerRadius.md)
                .fill(LinearGradient(
                    stops: [
                        .init(color: Color.white.opacity(colorScheme == .dark ? 0.08 : 0.35), location: 0.0),
                        .init(color: Color.clear, location: 0.55)
                    ],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                ))
                .allowsHitTesting(false)
        )
        .overlay(
            RoundedRectangle(cornerRadius: Theme.CornerRadius.md)
                .stroke(phaseTint.opacity(0.22), lineWidth: 0.75)
        )
    }
}
