name: UltraTrain
options:
  bundleIdPrefix: com.ultratrain
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"

targets:
  UltraTrain:
    type: application
    platform: iOS
    sources:
      - path: UltraTrain
        excludes:
          - "**/.DS_Store"
    resources:
      - path: UltraTrain/Resources
    dependencies:
      - target: UltraTrainWatch
        embed: true
      - target: UltraTrainWidgets
        embed: true
      - sdk: WatchConnectivity.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ultratrain.app
        INFOPLIST_FILE: UltraTrain/Resources/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: UltraTrain
        SWIFT_EMIT_LOC_STRINGS: "YES"
    entitlements:
      path: UltraTrain/Resources/UltraTrain.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    postCompileScripts: []

  UltraTrainWatch:
    type: application
    platform: watchOS
    sources:
      - path: UltraTrainWatch
        excludes:
          - "**/.DS_Store"
      - path: UltraTrain/Shared
        excludes:
          - "**/.DS_Store"
    resources:
      - path: UltraTrainWatch/Resources
    dependencies:
      - sdk: WatchConnectivity.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ultratrain.app.watchkitapp
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.ultratrain.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  UltraTrainWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: UltraTrainWidgets
        excludes:
          - "**/.DS_Store"
      - path: UltraTrain/Shared
        excludes:
          - "**/.DS_Store"
    resources:
      - path: UltraTrainWidgets/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ultratrain.app.widgets
        INFOPLIST_FILE: UltraTrainWidgets/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  UltraTrainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: UltraTrain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ultratrain.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/UltraTrain.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/UltraTrain"
        BUNDLE_LOADER: "$(TEST_HOST)"

  UltraTrainUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: UltraTrain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ultratrain.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: UltraTrain
