import Foundation

// swiftlint:disable:next identifier_name
private func _d(_ year: Int, _ month: Int, _ day: Int) -> Date {
    DateComponents(calendar: .current, year: year, month: month, day: day).date!
}

// MARK: - French Road Races

extension RaceDatabase {

    static let frenchRoadRaces: [KnownRace] = frenchMarathons + frenchHalfMarathons + frenchShortRoad + frenchFiveK

    // MARK: French Marathons

    private static let frenchMarathons: [KnownRace] = [
        KnownRace(name: "Marathon de Paris", shortName: "Paris Marathon", distanceKm: 42.195, elevationGainM: 292,
                  elevationLossM: 289, country: "France", nextEditionDate: _d(2026, 4, 12), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Lyon", shortName: nil, distanceKm: 42.195, elevationGainM: 50, elevationLossM: 50,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Bordeaux", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Toulouse", shortName: nil, distanceKm: 42.195, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Nantes", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 4, 26), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Marseille", shortName: nil, distanceKm: 42.195, elevationGainM: 60, elevationLossM: 60,
                  country: "France", nextEditionDate: _d(2026, 3, 29), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Nice-Cannes Marathon", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon du Médoc", shortName: nil, distanceKm: 42.195, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 9, 12), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Strasbourg", shortName: nil, distanceKm: 42.195, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 5, 17), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Lille", shortName: nil, distanceKm: 42.195, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 3, 22), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Montpellier", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 3, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon Vert Rennes", shortName: nil, distanceKm: 42.195, elevationGainM: 50, elevationLossM: 50,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon d'Annecy", shortName: nil, distanceKm: 42.195, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 4, 19), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de La Rochelle", shortName: nil, distanceKm: 42.195, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 11, 29), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Metz", shortName: nil, distanceKm: 42.195, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 10, 11), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon International du Beaujolais", shortName: nil, distanceKm: 42.195, elevationGainM: 60,
                  elevationLossM: 60, country: "France", nextEditionDate: _d(2026, 11, 21), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Tours", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 9, 20), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Vannes", shortName: nil, distanceKm: 42.195, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
        // Additional French marathons
        KnownRace(name: "Seine-Marathon 76", shortName: "Marathon de Rouen", distanceKm: 42.195, elevationGainM: 30,
                  elevationLossM: 30, country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de la Liberté", shortName: "Marathon de Caen", distanceKm: 42.195, elevationGainM: 40,
                  elevationLossM: 40, country: "France", nextEditionDate: _d(2026, 6, 7), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Le Havre", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 6, 7), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Grenoble", shortName: nil, distanceKm: 42.195, elevationGainM: 60, elevationLossM: 60,
                  country: "France", nextEditionDate: _d(2026, 5, 31), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Dijon", shortName: nil, distanceKm: 42.195, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marathon de Reims", shortName: nil, distanceKm: 42.195, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
    ]

    // MARK: French Half Marathons

    private static let frenchHalfMarathons: [KnownRace] = [
        KnownRace(name: "Semi de Paris", shortName: "Paris Half Marathon", distanceKm: 21.1, elevationGainM: 80,
                  elevationLossM: 155, country: "France", nextEditionDate: _d(2026, 3, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Boulogne-Billancourt", shortName: "Semi de Boulogne", distanceKm: 21.1,
                  elevationGainM: 20, elevationLossM: 20, country: "France", nextEditionDate: _d(2026, 11, 22),
                  terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Lille", shortName: nil, distanceKm: 21.1, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 9, 6), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Lyon", shortName: nil, distanceKm: 21.1, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Marseille", shortName: nil, distanceKm: 21.1, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 11, 1), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Nice", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 4, 26), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Montpellier", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Strasbourg", shortName: nil, distanceKm: 21.1, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Nantes", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 3, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Bordeaux", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 3, 22), terrainDifficulty: .easy, raceType: .road),
        // Additional French half marathons
        KnownRace(name: "Grenoble-Vizille", shortName: nil, distanceKm: 21.1, elevationGainM: 50, elevationLossM: 50,
                  country: "France", nextEditionDate: _d(2026, 3, 29), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Toulon", shortName: nil, distanceKm: 21.1, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 11, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi-Marathon Pegasus Caen", shortName: "Semi Pegasus", distanceKm: 21.1, elevationGainM: 20,
                  elevationLossM: 20, country: "France", nextEditionDate: _d(2026, 6, 7), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Reims", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Dijon", shortName: nil, distanceKm: 21.1, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Seine-Marathon 76 Semi", shortName: "Semi de Rouen", distanceKm: 21.1, elevationGainM: 15,
                  elevationLossM: 15, country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Saint-Étienne", shortName: nil, distanceKm: 21.1, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 11, 22), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "La Solidaire de Brest", shortName: "Semi de Brest", distanceKm: 21.1, elevationGainM: 30,
                  elevationLossM: 30, country: "France", nextEditionDate: _d(2026, 3, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Perpignan", shortName: nil, distanceKm: 21.1, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Toulouse Métropole Run Experience Semi", shortName: "Semi de Toulouse", distanceKm: 21.1,
                  elevationGainM: 20, elevationLossM: 20, country: "France", nextEditionDate: _d(2026, 11, 1),
                  terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi du Grésivaudan", shortName: nil, distanceKm: 21.1, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 5, 31), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi d'Annecy", shortName: nil, distanceKm: 21.1, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 4, 19), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Semi de Le Havre", shortName: nil, distanceKm: 21.1, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
    ]

    // MARK: French Short Road Races (10K, 20K, other)

    private static let frenchShortRoad: [KnownRace] = [
        // 20km+
        KnownRace(name: "Course Eiffage du Viaduc de Millau", shortName: "Viaduc de Millau", distanceKm: 23.7,
                  elevationGainM: 200, elevationLossM: 200, country: "France", nextEditionDate: _d(2026, 5, 17),
                  terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Marseille-Cassis", shortName: nil, distanceKm: 20.0, elevationGainM: 330, elevationLossM: 436,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "20km de Paris", shortName: nil, distanceKm: 20.0, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 10, 11), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Paris-Versailles", shortName: nil, distanceKm: 16.2, elevationGainM: 173, elevationLossM: 173,
                  country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        // Paris branded 10K
        KnownRace(name: "10km Adidas de Paris", shortName: "Adidas 10K Paris", distanceKm: 10.0, elevationGainM: 10,
                  elevationLossM: 10, country: "France", nextEditionDate: _d(2026, 6, 7), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "La Parisienne", shortName: nil, distanceKm: 6.7, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 9, 13), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Odysséa Paris", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Course Royale de Versailles", shortName: nil, distanceKm: 10.0, elevationGainM: 15,
                  elevationLossM: 15, country: "France", nextEditionDate: _d(2026, 6, 14), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Foulées de Vincennes", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 1, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Trail de Montmartre", shortName: nil, distanceKm: 10.0, elevationGainM: 200, elevationLossM: 200,
                  country: "France", nextEditionDate: _d(2026, 9, 20), terrainDifficulty: .moderate, raceType: .road),
        // Regional 10K
        KnownRace(name: "10km de Lyon", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 6, 14), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Marseille", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Bordeaux", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 5, 10), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Toulouse", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Nantes", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 9, 20), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Lille", shortName: nil, distanceKm: 10.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 9, 6), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Nice", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Cannes", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 11, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Strasbourg-Europe", shortName: nil, distanceKm: 10.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Montpellier", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 4, 19), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Rennes", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Tours", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 9, 20), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km d'Annecy", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 4, 19), terrainDifficulty: .easy, raceType: .road),
        // Corridas & classics
        KnownRace(name: "Corrida de Houilles", shortName: nil, distanceKm: 10.0, elevationGainM: 0, elevationLossM: 0,
                  country: "France", nextEditionDate: _d(2026, 12, 13), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Corrida de Langueux", shortName: nil, distanceKm: 10.0, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 6, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "Corrida de Noël d'Issy-les-Moulineaux", shortName: "Corrida d'Issy", distanceKm: 10.0,
                  elevationGainM: 10, elevationLossM: 10, country: "France", nextEditionDate: _d(2026, 12, 6),
                  terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de l'Équipe", shortName: nil, distanceKm: 10.0, elevationGainM: 40, elevationLossM: 40,
                  country: "France", nextEditionDate: _d(2026, 11, 22), terrainDifficulty: .easy, raceType: .road),
        // Additional French 10K races
        KnownRace(name: "10km de Grenoble", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 5, 10), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Clermont-Ferrand", shortName: nil, distanceKm: 10.0, elevationGainM: 30, elevationLossM: 30,
                  country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Dijon", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Rouen", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Caen", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 11), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Toulon", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 11, 8), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Le Havre", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Perpignan", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 11, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Saint-Étienne", shortName: nil, distanceKm: 10.0, elevationGainM: 25, elevationLossM: 25,
                  country: "France", nextEditionDate: _d(2026, 11, 22), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Brest", shortName: nil, distanceKm: 10.0, elevationGainM: 20, elevationLossM: 20,
                  country: "France", nextEditionDate: _d(2026, 3, 15), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Reims", shortName: nil, distanceKm: 10.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de Metz", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 10, 11), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km du Mans", shortName: nil, distanceKm: 10.0, elevationGainM: 15, elevationLossM: 15,
                  country: "France", nextEditionDate: _d(2026, 10, 4), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "10km de La Rochelle", shortName: nil, distanceKm: 10.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 11, 29), terrainDifficulty: .easy, raceType: .road),
    ]

    // MARK: French 5K Races

    private static let frenchFiveK: [KnownRace] = [
        KnownRace(name: "5km de Paris", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 9, 13), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Lyon", shortName: nil, distanceKm: 5.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 6, 14), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Marseille", shortName: nil, distanceKm: 5.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Bordeaux", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 5, 10), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Toulouse", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 11, 1), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Nantes", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 9, 20), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Lille", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 9, 6), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Strasbourg", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 5, 17), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Nice", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 4, 26), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Montpellier", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 4, 19), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Grenoble", shortName: nil, distanceKm: 5.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 5, 10), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Rouen", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 9, 26), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Rennes", shortName: nil, distanceKm: 5.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 10, 18), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Dijon", shortName: nil, distanceKm: 5.0, elevationGainM: 5, elevationLossM: 5,
                  country: "France", nextEditionDate: _d(2026, 10, 25), terrainDifficulty: .easy, raceType: .road),
        KnownRace(name: "5km de Clermont-Ferrand", shortName: nil, distanceKm: 5.0, elevationGainM: 10, elevationLossM: 10,
                  country: "France", nextEditionDate: _d(2026, 9, 27), terrainDifficulty: .easy, raceType: .road),
    ]
}
