import Foundation
import os

extension Logger {
    private static let subsystem = Bundle.main.bundleIdentifier ?? "com.ultratrain.app"

    static let app = Logger(subsystem: subsystem, category: "app")
    static let network = Logger(subsystem: subsystem, category: "network")
    static let training = Logger(subsystem: subsystem, category: "training")
    static let tracking = Logger(subsystem: subsystem, category: "tracking")
    static let nutrition = Logger(subsystem: subsystem, category: "nutrition")
    static let persistence = Logger(subsystem: subsystem, category: "persistence")
    static let fitness = Logger(subsystem: subsystem, category: "fitness")
    static let settings = Logger(subsystem: subsystem, category: "settings")
    static let healthKit = Logger(subsystem: subsystem, category: "healthKit")
    static let analysis = Logger(subsystem: subsystem, category: "analysis")
    static let haptic = Logger(subsystem: subsystem, category: "haptic")
    static let watch = Logger(subsystem: subsystem, category: "watch")
    static let liveActivity = Logger(subsystem: subsystem, category: "liveActivity")
    static let widget = Logger(subsystem: subsystem, category: "widget")
    static let export = Logger(subsystem: subsystem, category: "export")
    static let importData = Logger(subsystem: subsystem, category: "import")
    static let strava = Logger(subsystem: subsystem, category: "strava")
    static let notification = Logger(subsystem: subsystem, category: "notification")
    static let biometric = Logger(subsystem: subsystem, category: "biometric")
    static let cloudKit = Logger(subsystem: subsystem, category: "cloudKit")
    static let gear = Logger(subsystem: subsystem, category: "gear")
    static let liveRace = Logger(subsystem: subsystem, category: "liveRace")
    static let weather = Logger(subsystem: subsystem, category: "weather")
    static let pacing = Logger(subsystem: subsystem, category: "pacing")
    static let recovery = Logger(subsystem: subsystem, category: "recovery")
    static let checklist = Logger(subsystem: subsystem, category: "checklist")
    static let challenges = Logger(subsystem: subsystem, category: "challenges")
    static let workouts = Logger(subsystem: subsystem, category: "workouts")
    static let voiceCoaching = Logger(subsystem: subsystem, category: "voiceCoaching")
    static let ml = Logger(subsystem: subsystem, category: "ml")
    static let enhancedEstimator = Logger(subsystem: subsystem, category: "enhancedEstimator")
    static let social = Logger(subsystem: subsystem, category: "social")
    static let aiCoach = Logger(subsystem: subsystem, category: "aiCoach")
    static let safety = Logger(subsystem: subsystem, category: "safety")
    static let courseTracking = Logger(subsystem: subsystem, category: "courseTracking")
    static let achievements = Logger(subsystem: subsystem, category: "achievements")
}
