import Foundation
import Testing
@testable import UltraTrain

@Suite("DrawRouteUseCase Tests")
struct DrawRouteUseCaseTests {

    private let baseDate = Date(timeIntervalSince1970: 1_700_000_000)

    private func makeTrackPoint(
        lat: Double,
        lon: Double,
        alt: Double = 500,
        offsetSeconds: Double = 0
    ) -> TrackPoint {
        TrackPoint(
            latitude: lat,
            longitude: lon,
            altitudeM: alt,
            timestamp: baseDate.addingTimeInterval(offsetSeconds)
        )
    }

    private func makeTwoPoints() -> [TrackPoint] {
        [
            makeTrackPoint(lat: 45.832, lon: 6.865, alt: 1000, offsetSeconds: 0),
            makeTrackPoint(lat: 45.840, lon: 6.870, alt: 1200, offsetSeconds: 600)
        ]
    }

    // MARK: - Minimum Points

    @Test("Building route with 2 points succeeds")
    func buildRouteWithTwoPoints() throws {
        let points = makeTwoPoints()
        let route = try DrawRouteUseCase.buildRoute(name: "Test", trackPoints: points)
        #expect(route.trackPoints.count == 2)
        #expect(route.name == "Test")
    }

    @Test("Building route with fewer than 2 points throws insufficientData")
    func buildRouteWithOnePointThrows() {
        let singlePoint = [makeTrackPoint(lat: 45.832, lon: 6.865)]
        #expect(throws: DomainError.insufficientData(reason: "Route needs at least 2 points.")) {
            try DrawRouteUseCase.buildRoute(name: "Test", trackPoints: singlePoint)
        }
    }

    @Test("Building route with empty points throws insufficientData")
    func buildRouteWithEmptyPointsThrows() {
        #expect(throws: DomainError.insufficientData(reason: "Route needs at least 2 points.")) {
            try DrawRouteUseCase.buildRoute(name: "Test", trackPoints: [])
        }
    }

    // MARK: - Source

    @Test("Route source is manual")
    func sourceIsManual() throws {
        let route = try DrawRouteUseCase.buildRoute(
            name: "Manual Route",
            trackPoints: makeTwoPoints()
        )
        #expect(route.source == .manual)
    }

    // MARK: - Distance

    @Test("Distance is non-zero for spaced-apart points")
    func distanceIsNonZero() throws {
        let points = [
            makeTrackPoint(lat: 45.832, lon: 6.865, alt: 1000, offsetSeconds: 0),
            makeTrackPoint(lat: 45.930, lon: 6.960, alt: 1400, offsetSeconds: 3600)
        ]
        let route = try DrawRouteUseCase.buildRoute(name: "Long", trackPoints: points)
        #expect(route.distanceKm > 0)
    }

    // MARK: - Checkpoints

    @Test("Checkpoints are auto-generated when none provided")
    func autoGeneratedCheckpoints() throws {
        let points = [
            makeTrackPoint(lat: 45.832, lon: 6.865, alt: 1000, offsetSeconds: 0),
            makeTrackPoint(lat: 45.930, lon: 6.960, alt: 1400, offsetSeconds: 3600)
        ]
        let route = try DrawRouteUseCase.buildRoute(
            name: "Auto CP",
            trackPoints: points
        )
        // When no checkpoints are provided and the route is long enough,
        // auto-generation should produce at least start/finish
        #expect(route.checkpoints.isEmpty == false)
    }

    @Test("Custom checkpoints are preserved when provided")
    func customCheckpointsPreserved() throws {
        let customCheckpoints = [
            Checkpoint(
                id: UUID(),
                name: "Aid Station 1",
                distanceFromStartKm: 5,
                elevationM: 1200,
                hasAidStation: true
            ),
            Checkpoint(
                id: UUID(),
                name: "Summit",
                distanceFromStartKm: 10,
                elevationM: 2000,
                hasAidStation: false
            )
        ]
        let route = try DrawRouteUseCase.buildRoute(
            name: "Custom",
            trackPoints: makeTwoPoints(),
            checkpoints: customCheckpoints
        )
        #expect(route.checkpoints.count == 2)
        #expect(route.checkpoints[0].name == "Aid Station 1")
        #expect(route.checkpoints[1].name == "Summit")
    }

    // MARK: - Default Name

    @Test("Empty name defaults to My Route")
    func emptyNameDefaultsToMyRoute() throws {
        let route = try DrawRouteUseCase.buildRoute(
            name: "",
            trackPoints: makeTwoPoints()
        )
        #expect(route.name == "My Route")
    }
}
